name = "CSDNoise"
authors = ["Callum Arnold"]

[deps]
CSDNoiseCore = "8cb15dc8-b3ab-4164-9f0c-296b8d5139d2"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[sources]
CSDNoiseCore = {path = "CSDNoiseCore"}
